version: '2'

services:
  gateway:
    image: nginx:latest
    volumes:
      - /server/script/nginx:/etc/nginx
    ports:
      - "443:443"
      - "80:80"
    networks:
      - own

networks:
  own:
    external:
      name: activity