version: '2'

services:
  gateway:
    image: nginx:latest
    volumes:
      - /server/script/nginx:/etc/nginx
    ports:
      - "443:443"
      - "80:80"
    links:
      - service-end

networks:
  default:
    external:
      name: activity