version: '2'

services:
  gateway:
    image: txzdream/sysu-activityPlus-pc:dev
    volumes:
      - /server/script/nginx/ssl:/etc/nginx/ssl
      - /server/script/nginx/conf/:/etc/nginx/conf.d/:ro
    ports:
      - "443:443"
      - "80:80"
    networks:
      - own

networks:
  own:
    external:
      name: activity