# mysql listening on port 3306
# redis listening on port 6379
# service-end listening on port 8080
version: '2'

services:
  redis:
    image: redis
    volumes:
      - /server/data/dev/redis:/data/

  mysql:
    image: mysql:5.6
    volumes:
      - /server/data/dev/mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        
  mysql_client:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_ABSOLUTE_URI=/db
    links:
      - mysql

  service-end:
    image: xiaxzh/script:dev
    environment:
      - DEVELOP=true
      - PORT=8080
      - DATABASE_ADDRESS=mysql
      - DATABASE_PORT=3306
      - REDIS_ADDRESS=redis
      - REDIS_PORT=6379
    links:
      - redis
      - mysql
    expose:
      - 8080

  dev_gateway:
    image: nginx:latest
    volumes:
      - /server/script/dev/nginx:/etc/nginx:ro
    expose:
      - 80
    links:
      - service-end 
      - mysql_client
    networks:
      - share

networks:
  default:
    external:
      name: dev
  share:
    external:
      name: activity
    