# mysql listening on port 3306
# redis listening on port 6379
# service-end listening on port 8080
version: '2'

services:
  redis:
    image: redis
    volumes:
      - /server/data/production/redis:/data/

  mysql:
    image: mysql:5.6
    volumes:
      - /server/data/production/mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root

  service-end:
    image: xiaxzh/script
    environment:
      - DEVELOP=true
      - PORT=8080
      - DATABASE_ADDRESS=mysql
      - DATABASE_PORT=3306
      - REDIS_ADDRESS=redis
      - REDIS_PORT=6379
    links:
      - redis
      - mysql
    expose:
      - 8080

  production_gateway:
    image: nginx:latest
    volumes:
      - /server/script/production/nginx:/etc/nginx:ro
    expose:
      - 80
    links:
      - service-end
    networks: 
      - share

networks:
  default:
    external:
      name: production
  share:
    external:
      name: activity