# mysql listening on port 3306
# service-end listening on port 8080
version: '2'

services:

  mysql:
    image: mysql:5.6
    volumes:
      - /server/data/dev/mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
    networks:
      - share
    ports:
      - "5000:3306"
        
  mysql_client:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_ABSOLUTE_URI=/db
    links:
      - mysql
    networks:
      - share      

networks:
  share:
    external:
      name: activity
    
