# mysql listening on port 3306
# service-end listening on port 8080
version: '2'

services:

  pc-service-end:
    image: txzdream/sysu-activityplus-pc-service_end:dev
    volumes:
      - /server/static/dev:/data/static
    environment:
      - DEVELOP=TRUE
      - PORT=8080
      - DATABASE_ADDRESS=mysql
      - DATABASE_PORT=3306
      - STATIC_DIR=/data/static
      - MQ_ADDRESS=pc-message-queue
      - MQ_USER=root
      - MQ_PASSWORD=root
    expose:
      - 8080
    networks:
      - share

  # pc-message-queue:
  #   image: rabbitmq:3-management
  #   hostname: sysuactivity.com
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=root
  #     - RABBITMQ_DEFAULT_PASS=root
  #   networks:
  #     - share

  # pc-mail-service:
  #   image: txzdream/sysu-activityplus-pc-mail-service:dev
  #   environment:
  #     - ADMIN_MAIL_PASS=T3Y2vAX3i1jH
  #     - MQ_ADDRESS=pc-message-queue
  #     - MQ_USER=root
  #     - MQ_PASSWORD=root
  #   networks:
  #     - share
  #   depends_on: 
  #     - pc-message-queue
  #   restart: always

  pc-gateway:
    image: nginx:latest
    volumes:
      - /server/script/pc/nginx:/etc/nginx/conf.d/:ro
    expose:
      - 80
    links:
      - pc-service-end
    networks:
      - share
      

networks:
  share:
    external:
      name: activity
    
